version: "3.5"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: microservice
    volumes:
        - ./init/01-create-db.sql:/docker-entrypoint-initdb.d/01-create-db.sql
        - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  zookeeper:
    container_name: zookeeper
    image: "docker.io/bitnami/zookeeper:3"
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

volumes:
  zookeeper_data:
    driver: local
  postgres_data:
    driver: local