server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    routes:
      - id: auth-service
        uri: http://localhost:8090  # Load balanced URI
        predicates:
          - Path=/auth/**  # Adjust this
      - id: user-service
        uri: http://localhost:8091  # Load balanced URI
        predicates:
          - Path=/user/**
      - id: garment-service
        uri: http://localhost:8092  # Load balanced URI
        predicates:
          - Path=/clothes/**  # Adjust this
    gateway:
      discovery:
        locator:
          enabled: true
      httpclient:
        connect-timeout: 60000
        response-timeout: 60s